### ISSUE TITLE
Monthly forward rates

### ISSUE THREAD

**Issue by pdavidsonFIA** [DeNederlandscheBank/solvency2-data-science#4]
I need monthly forward rates. What would be the most efficient way to derive these from this package? Does the smith-wilson work correctly for interpolating between annual spot rates?

**Comment by wjwillemse** [comment]
Smith-Wilson might work for interpolation. But the problem is that if you apply the SW-algorithm on the liquid points of the published data you don't get the published curve in return. EIOPA applies the SW-algorithm on (raw) observed rates and it publishes rates rounded to three decimal places. So if you would run the algorithm with these published rates you get slightly different SW-parameters and slight different rates for the non-liquid points. Why not use linear splines interpolation?

**Comment by pdavidsonFIA** [comment]
Good suggestion and very easy to implement :) thanks!
